name: Pull Markdown Files

on:
  repository_dispatch:
    types: [docs_changed]

jobs:
  pullMarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: master
          path: './temp'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Copy Files
        run: |
          const fs = require('fs');
          const path = require('path');
          const glob = require('glob');
          const targetPath = `./docs/${{ github.event.client_payload.name }}`;
          if (!fs.existsSync(targetPath)) {
            fs.mkdirSync(targetPath, { recursive: true });
          }
          fs.copyFileSync('./temp/README.md', path.join(targetPath, 'README.md'));
          const docFiles = glob.sync('./temp/docs/**/*.md');
          docFiles.forEach((file) => {
            const targetFile = file.replace('./temp/', targetPath + '/');
            fs.copyFileSync(file, targetFile);
          });

      - name: Remove Temp Directory
        run: |
          const fs = require('fs');
          const path = require('path');
          const directory = './temp';
          fs.rmdirSync(directory, { recursive: true });

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DOCS_PAT }}
          commit-message: "Merge new docs from ${{ github.event.client_payload.repository }}"
          branch: "${{ github.event.client_payload.repository }}-${{ github.run_id }}"
          delete-branch: true
          title: "Update docs from ${{ github.event.client_payload.repository }}"
          body: "This PR merges documentation updates from ${{ github.event.client_payload.repository }}"
          labels: "documentation, automated pr"
          draft: false
