name: Pull Markdown Files

on:
  repository_dispatch:
    types: [docs_changed]

jobs:
  pullMarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Package Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: master
          path: './temp'

      - name: Copy Files
        run: |
          mkdir -p "./src/app/docs/${{ github.event.client_payload.name }}"
          cp "./temp/README.md" "./src/app/docs/${{ github.event.client_payload.name }}/page.md"

      - name: Remove Temp Directory
        run: rm -rf "./temp"

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Merge new docs from ${{ github.event.client_payload.repository }}"
          branch: "${{ github.event.client_payload.repository }}-${{ github.run_id }}"
          title: "Update docs from ${{ github.event.client_payload.repository }}"
          body: "This PR merges documentation updates from ${{ github.event.client_payload.repository }}"
          labels: "documentation, automated pr"
          delete-branch: true
          draft: false
